### ISSUE TITLE
Plan the project in board and roadmap in GitHub

### ISSUE THREAD

**Issue by H-chai** [NoroffFEU/fed2-js2-ca-H-chai#2]
- [x] Accept the GitHub Classroom invitation
- [x] Create GitHub project
- [ ] Create roadmap for each task/issue
